# UV configuration file

# Python preference
python-preference = "only-managed"

# Cache configuration  
cache-dir = ".uv-cache"

# Resolution strategy
resolution = "highest"

# Index configuration
index-url = "https://pypi.org/simple"

# Upgrade packages by default
upgrade = true
